# Use the official Ubuntu base image
FROM ubuntu:latest

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y apache2 && \
    apt-get install -y squashfs-tools && \
    apt-get clean

# Copy the flag.txt to the Docker image
COPY notflag.txt /tmp/flag.txt

# Create the website directory and copy the website files
RUN mkdir -p /var/www/html

# Copy the generated index.html file to the web server directory
COPY index.html /var/www/html/index.html

# Create a hidden folder in the home directory with a hint
RUN echo "  - Make website secure" > /root/todo.txt

# Set the entrypoint to bash for interactive use
ENTRYPOINT ["/bin/bash"]